#cloud-config
# https://www.techrepublic.com/article/how-to-install-neo4j-ubuntu-server/
users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCPIIO8uY8oWIihDv0tCAbX6toyG1RYkaLZyfGD1L+I07K4CnwAVBSU+81vw3Yv5sN9tj2Ccve9kzEeCNMld2mDP/Tt7edkx2MCToVfVx+njqwY/XbMY9bfdRKJLhIoLavuVNLnnkSIXdtlGr3JF71hPHzBDMEo64ofPCQ8hPsGxL1u3efb12jcWcRhudKtv7Qh6cVE47Zj4xImfi6VlLqwzcKZ5oCqR/z1hLLL+/pS3eM5Qsor5wmAqNfH4+z5eE+pOkFm7a0Nkygv9jwXIqtJzFGKYDe6ciBD04pEovdvY0FTyiv2vksQOVgjtu2faG2Iv1HOG0JktCIwJ49OEgjT teacher-key
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDRI4IqTl6RNGbOJlpVLT6qSuRa34FqHtdOQaq1vxgTPPDesHMGrTIM2jaS2S6HgKMgW3C8COFXR23SQAcyF2C9G+H4MzTge/dmpFDJh3ram2N7HC/N1tB76W0nA05aQWvDHAHSqqB20pAstxvtq8DteGERCNj6sl9GRKDxwXdAthuRXwq+dM05cq6T7vDki/yMmJUYRmyGBEzKfci6XYBMQ079I/4x33NGGqsK23wFb3khqziCUTRtCwJe7frX9Z1ak2JG9RMdEf4l/5kGjOez0VptMcpdZM4C7uyklFtGIb9OjAPLHowgq0cCB9bL7h86U5FkdejLkC87Uzhm/Fo7 teacher-key
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKCuWX/W66sjjNiDNuPpKgYO1xFqDoMJoeo5hz2LDNrF teacher-key-wir
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDb3G0Bp763wCh6RH2/z++b/+xxp6f2BCtUHFD3YpUAzpZigg7V5abUiuSyElZvlFsQBdJjaqkIjT6x+mCnGGKi5TP/wIDvFApFgNfO07MRD5DK4Bd/0mRZs5BrPlUqWLUQeXYUd4uXJAQ7Ev0yqIp1vMJMUmOkb7khi1RIzimeTimGm/bSrXfsTbBiwB+cneqhPpvlamB4pXgHxk1lUkCRe1EYj+d0jxyGVDPvusPIi6KaThYYnlRQAA19cdyVx+YwaHcq+pDy2WMXJSUizX/DXXfjxT5/r4ryLrsJLzYAULbxKBYoZo1YPrWRmpdGD/eaqQy+mAt6ykN8BvMBClyR
 
ssh_pwauth: false
disable_root: false    
package_update: true 
packages:
  - unzip
  - gnupg
  - curl
runcmd:
  - curl -fsSL https://debian.neo4j.com/neotechnology.gpg.key |sudo gpg --dearmor -o /usr/share/keyrings/neo4j.gpg
  - echo "deb [signed-by=/usr/share/keyrings/neo4j.gpg] https://debian.neo4j.com stable latest" | sudo tee -a /etc/apt/sources.list.d/neo4j.list
  - sudo apt-get update -y
  - sudo apt install neo4j -y
  - sudo systemctl enable neo4j.service
  - sudo systemctl start neo4j.service
  - sudo sed -i 's/#server.default_listen_address/server.default_listen_address/g' /etc/neo4j/neo4j.conf
  - sudo systemctl restart neo4j.service
# default username and password are "neo4j" (without the quotes)
